services:
  dash:
    build: .
    ports:
      - '5174:5173'
    volumes:
      - dash_data:/app   # Un solo volumen persistente para toda la aplicación
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - tools_dash_network

# Definición de redes
networks:
  tools_dash_network:
    driver: bridge

# Definición de volúmenes
volumes:
  dash_data:
    driver: local